services:
  postgis:
    container_name: postgis-db
    image: kartoza/postgis:16-3.4
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgis-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      postgis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    platform: linux/amd64
    volumes:
      - ./shared:/shared
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_DOMAIN=${VITE_API_DOMAIN}
      - VITE_API_PROTOCOL=${VITE_API_PROTOCOL}
      - VITE_MAPTILER_API_KEY=${VITE_MAPTILER_API_KEY}
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgis-data:
    driver: local

networks:
  app-network:
    driver: bridge
