services:
  backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - '3000:3000'
    command:
      - /bin/bash
      - -c
      - |
        exec uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload --reload-dir /app
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=production

  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    platform: linux/amd64
    ports:
      - '5173:5173' # Development port
      - '80:80' # Production port
    volumes:
      - ./shared:/shared
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  postgis:
    container_name: postgis-db
    image: kartoza/postgis:16-3.4
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgis-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  postgis-data:
    driver: local
