name: Monthly Data Update

on:
  schedule:
    - cron: '10 11 3 * *' # Runs at 11:06 AM (MST) on the 3rd of every month
    # - cron: '0 10 1 * *' # Runs at 3 AM (MST) on the 1st of every month
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip3 install --no-cache-dir fastapi uvicorn[standard] psycopg2-binary shapely numpy osmnx networkx scikit-learn geopandas python-multipart orjson

      - name: Grant execute permissions to the script
        run: chmod +x seed/generate_seed_data.py

      - name: Run the update script
        run: |
          python3 seed/generate_seed_data.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update data"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Grant execute permissions to the run-pod script
        run: chmod +x deploy/run-pod.sh

      - name: Run the run-pod script
        run: |
          set -a
          echo "KEY_PAIR_FILE=deploy/walkernest-key-pair.pem" >> .env
          chmod 600 deploy/walkernest-key-pair.pem
          echo "USER=${{ secrets.USER }}" >> .env
          echo "DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}" >> .env
          echo "INSTANCE_IP=${{ secrets.INSTANCE_IP }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "RUN_SEED=${{ secrets.RUN_SEED }}" >> .env
          echo "VITE_API_DOMAIN=${{ secrets.VITE_API_DOMAIN }}" >> .env
          echo "VITE_API_PROTOCOL=${{ secrets.VITE_API_PROTOCOL }}" >> .env
          echo "VITE_MAPTILER_API_KEY=${{ secrets.VITE_MAPTILER_API_KEY }}" >> .env
          set +a
          ./deploy/run-pod.sh
